title: Josh Branchaud
description: a blog about my adventures with and without code

baseurl: '/blog' 
permalink: /blog/:categories/:year/:month/:day/:title.html

markdown: kramdown

redcarpet:
    extensions: ["fenced_code_blocks","footnotes"]

highlighter: rouge

exclude: ['README.md',
          'package.json',
          'node_modules',
          'Gruntfile.js',
          'bower.json',
          'bower_components',
          'Gemfile',
          'Gemfile.lock']
